server:
  port: 8071

spring:
  security:
    basic:
      enabled: false
  application:
    name: discovery

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZoon: http://${eureka.instance.hostname}:${server.port}/eureka/
