server:
  port: 8072

spring:
  security:
    basic:
      enabled: false
  application:
    name: restaurant-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZoon: http://${eureka.instance.hostname}:8071/eureka/
